imports:
    - { resource: ../app/config/parameters.yml }
    - { resource: ../vendor/webfactory/symfony-default-config/config.yml }
    - { resource: ../vendor/webfactory/doctrine-bundle-default-config/config.yml }

parameters:
    app.kiln.token:
    app.github.token:
